[package]
name = "aoc2021_10"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "u1"
path = "1.rs"

[[bin]]
name = "u2"
path = "2.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

